### ISSUE TITLE
Error Invalid version: '0.23ubuntu1' on "colcon build --symlink-install" inside Docker container

### ISSUE THREAD

**Issue by Lanzo98** [NVIDIA-ISAAC-ROS/isaac_ros_apriltag#21] opened 2023-01-26 10:00 UTC
Following the Quickstart guide a step 5, the build of the workspace inside docker gives the following error:
`pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '0.23ubuntu1' (package: distro-info)`

Seems it is correlated with this [issue](https://github.com/pypa/setuptools/issues/3772) relative to the version of Python Setuptools. Downgrading from version 66 to 65 solved the building problem in my case. However, this is only a workaround and the project should adapt to provide conformant versions during the build.

**Comment by hemalshahNV** [comment] 2023-01-30 23:16
We have started seeing this locally as well on aarch64 only and debugging it now. Duplicate of https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_visual_slam/issues/71

**Comment by hemalshahNV** [comment] 2023-01-31 23:15
We've reverted the change to the latest Isaac ROS Dev base image for aarch64 which includes the updated setuptools. We'll update the image again with the issue corrected or the version anchored properly. Thanks for your help!

**Comment by Lanzo98** [comment] 2023-02-01 06:41
Okay, perfect. Can you share the steps for making the apriltag work directly into the nx without the docker image?

**Comment by hemalshahNV** [comment] 2023-02-05 06:20
Isaac ROS Apriltag does not have many dependencies beyond ROS2 Humble on Jetpack 5.0.2. You can use the commands from Dockerfile.humble to build ROS2 from source if you haven't already.

**Comment by Lanzo98** [comment] 2023-02-05 06:33
I have installed ROS Humble from source following this [ROS guide](https://docs.ros.org/en/humble/Installation/Alternatives/Ubuntu-Development-Setup.html). Is it the same or do I need to follow the different steps done in [Dockerfile.humble](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/blob/main/docker/Dockerfile.humble)?

**Comment by hemalshahNV** [comment] 2023-02-14 00:40
There are specific versions of system libraries (cmake, and others) that we have pinned for you in Dockerfile.aarch64 and Dockerfile.humble to make compiling from source smooth. However, if you have ROS 2 Humble built from source successfully, then you should try running Isaac ROS packages and see how it goes.

**Closed** 2023-04-17 23:46 UTC
Labels: bug, verify to close
